### ISSUE TITLE
Can't compile: `Ambiguous occurrence ‘typeOf’`

### ISSUE THREAD

**Issue by L-as** [ollef/sixty#4]
I tried compiling with both GHC 8.6.5 and 8.10.1 (had to update constraints-extras for this one), but I get the following errors:
```

src/ClosureConverted/TypeOf.hs:38:9: error:
    Ambiguous occurrence ‘typeOf’
    It could refer to
       either ‘Protolude.typeOf’,
              imported from ‘Protolude’ at src/ClosureConverted/TypeOf.hs:5:1-30
              (and originally defined in ‘Data.Typeable’)
           or ‘ClosureConverted.TypeOf.typeOf’,
              defined at src/ClosureConverted/TypeOf.hs:77:1
   |
38 |         typeOf context value
   |         ^^^^^^

src/ClosureConverted/TypeOf.hs:65:19: error:
    Ambiguous occurrence ‘typeOf’
    It could refer to
       either ‘Protolude.typeOf’,
              imported from ‘Protolude’ at src/ClosureConverted/TypeOf.hs:5:1-30
              (and originally defined in ‘Data.Typeable’)
           or ‘ClosureConverted.TypeOf.typeOf’,
              defined at src/ClosureConverted/TypeOf.hs:77:1
   |
65 |       bodyType <- typeOf context body'
   |                   ^^^^^^

src/ClosureConverted/TypeOf.hs:120:11: error:
    Ambiguous occurrence ‘typeOf’
    It could refer to
       either ‘Protolude.typeOf’,
              imported from ‘Protolude’ at src/ClosureConverted/TypeOf.hs:5:1-30
              (and originally defined in ‘Data.Typeable’)
           or ‘ClosureConverted.TypeOf.typeOf’,
              defined at src/ClosureConverted/TypeOf.hs:77:1
    |
120 |           typeOf context value'
    |           ^^^^^^

src/ClosureConverted/TypeOf.hs:136:19: error:
    Ambiguous occurrence ‘typeOf’
    It could refer to
       either ‘Protolude.typeOf’,
              imported from ‘Protolude’ at src/ClosureConverted/TypeOf.hs:5:1-30
              (and originally defined in ‘Data.Typeable’)
           or ‘ClosureConverted.TypeOf.typeOf’,
              defined at src/ClosureConverted/TypeOf.hs:77:1
    |
136 |                   typeOf context body'
    |                   ^^^^^^

src/ClosureConverted/TypeOf.hs:181:7: error:
    Ambiguous occurrence ‘typeOf’
    It could refer to
       either ‘Protolude.typeOf’,
              imported from ‘Protolude’ at src/ClosureConverted/TypeOf.hs:5:1-30
              (and originally defined in ‘Data.Typeable’)
           or ‘ClosureConverted.TypeOf.typeOf’,
              defined at src/ClosureConverted/TypeOf.hs:77:1
    |
181 |       typeOf context branch'

```

**Comment by ollef** [comment]
Hey!

It looks like you're not using the same version of the `protolude` package as I am. I use Stack for developing this code, so the exact versions that Sixty has been tested against can be found in the current Stackage snapshot (15.5 at the moment) and under `extra-deps` in `stack.yaml`. It looks like `protolude` is on version 0.2.4 in the snapshot, so that's the only version known to work.

I realise that not everyone uses Stack though, so it would be good to support other workflows, like Cabal. Would you like to help with that? I'm guessing there should be version bounds in the cabal file, and that `typeOf` should sometimes be hidden in the import of `Protolude` if we want a wider compatibility range.

Thanks for the report!

**Comment by L-as** [comment]
Thanks! I am using cabal since I couldn't figure out how to make stack use my own version of GHC (am on aarch64 NixOS and it always tries to build GHC... which takes around 12 hours for me). I'll try making it work on cabal.

**Comment by L-as** [comment]
FWIW it seems to work fine with protolude version 0.3, will make a PR after some more testing.
